travis:
  secure:
    BINSTAR_TOKEN: Nb85u0IoFISJi+w296pmyG9rHay5tXpIOZVEXDnrBg9nJllZyNUj3E005qpjf6SueuOch9tCwRrAGKFN0604sCZxa8ESxskKGKf3eTSDPzLrQJltWjbrLPNxzMi18SKbTKcTBHK9XqsaFnJMl99kmjRfi+7i5VQ11dXugy6au5rzRg/ydD7fLiXuAz2HOSjb3dYNMWKNnqdU+bob6gUGAtyRqrHWiRJ5+3zKwg2OP5mm4TrsWr7tr8+8c9VnFlGw/G55QpMAfS+JeXQWLteqW1r05c4gYDZz1VmegCZjUDKZOoXYhq5gxsb68WGXRICsGW8LQymuFsA5Xc6hHzaWFiphbBg3nO0GqaCJDAEjsZ/KvZ9MxggthYJ6m76fbBUAgI2taPcnD78imlRoTVLcvqj7AtMLyE+ijAR3visirReA3FjlZnDOUdixNtdgPakvKh8RPzDyvZt0cNTGzDNNPmRDxoyV4nvY6SDy7dR4tZe2mBVtEyRpi38WXQAzJ3PH4ajNKz1SGVHVu5Rx74YykAgx9xyaw2lmmFc+vvWwTsBs+VHfBKdsZ4ZUcAcxwPXfbNpRe5MDeYjedENfPCf9MTu7OUeo5o53QKxLx8cN5WKa5bjDOruNGIEs5mr3QLgaODD8Tev6ETzW+5ObMecreaIL8GB0xo5ftsbwk22Gsow=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
